# Dataset and previous model
folder: 'dataset/2022-10-09'
training_fraction: 1.0
random_dataset: False
batch_size: 10000
shuffle: True
num_workers: 0

# Model
load_folder: null
nn_widths: [32, 32, 32]
activation_function: 'elu'

# Technical parameters
device : 'cuda:0' 
dtype: 'float32'

# Training
epochs : 50
optimizer : 'AdamW'
log_lr: -1
log_weight: -4
loss_func : 'final-mse-pos'
normalize_loss : True

# Scheduling
scheduler: 'LambdaLR'
scheduling_factor: 0.8
scheduling_freq: 500

# Neural ODE parameters
dataset_steps: 2
steps_per_dt: 4

# Evaluation
eval_dataset_steps: 2
eval_steps_per_dt: 4
eval_init_skip: 100
evaluation_freq: 5

# Early stopping
stopping_freq: 20
stopping_look_back: 2

# Checkpointing
checkpoint_freq: 3

# W&B Logging
wandb: True
sweep: True
project: 'cg-node-hexagon'
sweep_id: null
n_count: 50